services:

  sys_logger:
    build: .
    container_name: sys_logger
    restart: unless-stopped
    privileged: true  # Для доступа к системной информации
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=k4h5k8ow7
      - POSTGRES_DB=server_stats
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - TZ=Europe/Moscow
    # Проброс устройств для доступа к температуре
    devices:
      - /dev:/dev
    # Проброс системных путей для доступа к информации о температуре
    volumes:
      - ./logs:/logs
      - /sys/class/thermal:/sys/class/thermal:ro
      - /sys/devices:/sys/devices:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    stop_signal: SIGTERM
    stop_grace_period: 10s
    networks:
      - db
    # Устанавливаем режим доступа к хостовой системе
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - SYS_PTRACE


networks:
  db:
    external: true
    name: db