services:

  sys_logger:
    build: .
    container_name: syslogger
    restart: unless-stopped
    privileged: true  # Для доступа к системной информации
    environment:
      - TZ=Europe/Moscow
    devices:
      - /dev:/dev # Проброс устройств для доступа к температуре
    volumes: # Проброс системных путей для доступа к информации о температуре
      - /home/ivan/DockerData/SysLogger/logs:/logs
      - /sys/class/thermal:/sys/class/thermal:ro
      - /sys/devices:/sys/devices:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    stop_signal: SIGTERM
    stop_grace_period: 10s
    networks:
      - db
    cap_add: # Устанавливаем режим доступа к хостовой системе
      - SYS_ADMIN
      - SYS_RAWIO
      - SYS_PTRACE


networks:
  db:
    external: true
    name: db